name: HomeBukkit
main: com.dinnerbone.bukkit.home.HomeBukkit
version: 0.0.1
website: http://www.bukkit.org
author: The Bukkit Team
database: true
description: >
             Basic home functionality.
             This plugin is one of the default plugins shipped with Bukkit.
commands:
  sethome:
    aliases: [addhome]
    description: Sets your current position to a home of the given name
    usage: |
           /<command> <name> [player]
           Example: /<command> BeachHouse
  listhomes:
    aliases: [homes]
    description: Lists all homes that you own
    usage: /<command> [player]
  gohome:
    aliases: [home]
    description: Goes to a home
    usage: /<command> <name> [player]
permissions:
  homebukkit.set:
    description: allows the player to set homes
    children:
          homebukkit.set.self: true
          homebukkit.set.other: true
  homebukkit.set.self:
    description: Allows the player to set their own home
  homebukkit.set.other:
    description: Allows the player to set other peoples homes
  homebukkit.list:
    description: Allows the player to list theirs and other players homes
    children: 
          homebukkit.list.self:true
          homebukkit.list.other:true
  homebukkit.list.self:
    description: Allows the player to list their homes
  homebukkit.list.other:
     description: Allows the player to list others homes
  homebukkit.home:
    description: allows the player to teleport to his/others homes
    chidren:
         homebukkit.set.self:true
         homebukkit.set.other:true
  homebukkit.home.self:
    description: Allows the player to teleport to their home
  homebukkit.home.other:
    description: Allows the player to teleport to other players home

  homebukkit.*:
    description: Gives all permissions for HomeBukkit
    default: op
    children:
      homebukkit.set: true
      homebukkit.list: true
      homebukkit.home: true
  